#!/bin/bash

# original author: Geoff Franks (Stark & Wayne)
# created:         2016-05-13
# maintainer:      Benjamin Gandon (Gstack)

set -e

export GOPATH=${PWD}/gopath
export PATH=${PATH}:${GOPATH}/bin
cd ${GOPATH}/src/${MODULE}


go version; echo; echo
go vet $(go list ./... | grep -v vendor)
go test -v ./...
