---
meta:
  name:    yasak
  target:  (( grab meta.team ))
  url:     https://ci.gstack.io
  team:    gk-plat-devs

  initial_version: 1.0.0

  go:
    version: "1.16"
    binary: yasak
    cmd_module: .

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-1
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  gstackio
    repo:   yasak
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       "#pipelines-notifications"

  credhub:
    client: concourse-gk-plat-devs-to-credhub


groups:
  - name: setup
    jobs:
      - set-github-webhooks

jobs:
  - name: set-github-webhooks
    serial: true
    plan:
      - get: concourse-webhook-token
        trigger: true
      - put: create-webhook
        resource: github-webhook
        params:
          org:           (( grab meta.github.owner ))
          repo:          (( grab meta.github.repo ))
          resource_name: git
          webhook_token: ((concourse-webhook-token))
          operation:     create
          events:        [ push ]

resources:

  - name: git
    webhook_token: ((concourse-webhook-token))
    check_every: 24h

  - name: version
    type: semver
    source:
      bucket:            (( prune ))
      region_name:       (( prune ))
      key:               (( prune ))
      access_key_id:     (( prune ))
      secret_access_key: (( prune ))
      driver:      git
      uri:         git@github.com:gstackio/gk-pipelines-compass.git
      branch:      master
      file:        (( concat "versions/" meta.pipeline ))
      private_key: ((github-private-key))
      git_user:    "((git-commit-name)) <((git-commit-email))>"

  - name: github-webhook
    type: github-webhook-resource
    source:
      github_api:   https://api.github.com
      github_token: (( grab meta.github.access_token ))

  - name: concourse-webhook-token
    type: credhub-secret
    source:
      server: https://credhub.ci.gstack.io
      username: (( grab meta.credhub.client ))
      password: ((credhub-client-secret))
      path: (( concat "/concourse/" meta.team "/concourse-webhook-token" ))

resource_types:

  - name: credhub-secret
    type: docker-image
    source:
      repository: cfcommunity/credhub-resource

  - name: github-webhook-resource
    type: docker-image
    source:
      repository: homedepottech/github-webhook-resource
