---
meta:
  name:    yasak
  target:  (( grab meta.team ))
  url:     https://ci.gstack.io
  team:    gk-plat-devs

  initial_version: 1.0.0

  go:
    version: "1.16"
    binary: yasak
    cmd_module: .

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-1
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  gstackio
    repo:   yasak
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       "#pipelines-notifications"

  credhub:
    client: concourse-gk-plat-devs-to-credhub


groups:
  - name: setup
    jobs:
      - set-github-webhooks
      - delete-github-webhooks

jobs:
  - name: set-github-webhooks
    serial: true
    serial_groups: [ github-webhooks ]
    plan:
      - get: concourse-webhook-token
        trigger: true
      - put: create-repo-webhook
        resource: github-webhook
        params:
          operation:     create
          resource_name: git
          events:        [ push ]
          <<: &github_webhook_resource_params
            org:           (( grab meta.github.owner ))
            repo:          (( grab meta.github.repo ))
            webhook_token: ((concourse-webhook-token))
      - put: create-pr-webhook
        resource: github-webhook
        params:
          operation:     create
          resource_name: git-pull-requests
          events:        [ push, pull_request ]
          <<: *github_webhook_resource_params

  - name: delete-github-webhooks
    serial: true
    serial_groups: [ github-webhooks ]
    plan:
      - put: delete-repo-webhook
        resource: github-webhook
        params:
          operation:     delete
          resource_name: git
          events:        [ push ]
          <<: *github_webhook_resource_params
      - put: delete-pr-webhook
        resource: github-webhook
        params:
          operation:     delete
          resource_name: git-pull-requests
          events:        [ push, pull_request ]
          <<: *github_webhook_resource_params

  - name: test
    plan:
      - do:
        - (( append ))
        - get: build-container
          trigger: true
        - task: compile
          image: build-container
          config:
            platform: linux
            inputs:
              - name: git
            outputs:
              - name: compiled-binary
            run:
              dir: git
              path: go
              args:
                - build
                - -o
                - ../compiled-binary/yasak
        - task: test
          image: build-container
          config:
            platform: linux
            inputs:
              - name: compiled-binary
              - name: git
            run:
              path: sh
              args:
                - -exc
                - |
                  export PATH=${PWD}/compiled-binary:${PATH}

                  yasak locate --path "/bim/bam" git/test/fixture1.yml > result1
                  diff -u git/test/expected1 result1

                  apk add bash
                  git/example-edit-value.sh "git/test/fixture2.yml" "/bim/bam/toto" "plop" > result2.yml
                  diff -u result2.yml git/test/expected2.yml

resources:

  - name: version
    type: semver
    source:
      bucket:            (( prune ))
      region_name:       (( prune ))
      key:               (( prune ))
      access_key_id:     (( prune ))
      secret_access_key: (( prune ))
      driver:      git
      uri:         git@github.com:gstackio/gk-pipelines-compass.git
      branch:      master
      file:        (( concat "versions/" meta.pipeline ))
      private_key: ((github-private-key))
      git_user:    "((git-commit-name)) <((git-commit-email))>"

  - name: git
    webhook_token: ((concourse-webhook-token))
    check_every: 24h

  - name: git-pull-requests
    webhook_token: ((concourse-webhook-token))
    # check_every: 1m # we leave the default here

  - name: github-webhook
    type: github-webhook-resource
    source:
      github_api:   https://api.github.com
      github_token: (( grab meta.github.access_token ))

  - name: concourse-webhook-token
    type: credhub-secret
    source:
      server: https://credhub.ci.gstack.io
      username: (( grab meta.credhub.client ))
      password: ((credhub-client-secret))
      path: (( concat "/concourse/" meta.team "/concourse-webhook-token" ))

  - name: build-container
    type: docker-image
    icon: docker
    source:
      repository: golang
      tag: (( concat meta.go.version "-alpine" ))
    check_every: 24h

resource_types:

  - name: credhub-secret
    type: docker-image
    source:
      repository: cfcommunity/credhub-resource

  - name: github-webhook-resource
    type: docker-image
    source:
      repository: homedepottech/github-webhook-resource
