name: Trigger Concourse git resource
on: [ push, workflow_dispatch ]
jobs:
  trigger-resource-check:
    runs-on: ubuntu-latest
    steps:
      # - name: Trigger a resource check in Concourse
      #   env:
      #     CONCOURSE_WEBHOOK_TOKEN: ${{ secrets.CONCOURSE_WEBHOOK_TOKEN }}
      #   run:
      #     curl --silent --fail --show-error --location
      #         --request "POST"
      #         --url "https://ci.gstack.io/api/v1/teams/gk-plat-devs/pipelines/yasak/resources/git/check/webhook?webhook_token=${CONCOURSE_WEBHOOK_TOKEN}"
      - name: Trigger resource check
        uses: gstackio/trigger-concourse-resource-check-action@master
        with:
          concourse-url:           https://ci.gstack.io
          concourse-team:          gk-plat-devs
          concourse-pipeline:      yasak
          concourse-resource:      git
          concourse-webhook-token: ${{ secrets.CONCOURSE_WEBHOOK_TOKEN }}
