name: Concourse resource-check trigger
on: [ push, pull_request ]
jobs:
  trigger-resource-check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger resource check
        uses: gstackio/trigger-concourse-resource-check-action@master
        with:
          concourse-url:      https://ci.gstack.io
          concourse-team:     gk-plat-devs
          concourse-pipeline: yasak
          concourse-resource: git-pull-requests
